import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Terms for using proxy-agent",
};

export default function TermsOfService() {
  return (
    <main style={{ maxWidth: 760, margin: "0 auto", padding: "80px 24px" }}>
      <h1 style={{ fontSize: 40, marginBottom: 8 }}>Terms of Service</h1>
      <p className="muted" style={{ marginBottom: 40 }}>
        Last updated: September 25, 2025
      </p>

      <h2>1. Agreement</h2>
      <p>
        By creating an account or using proxy-agent (&quot;the
        service&quot;), you agree to these terms. If you do not agree, do not
        use the service.
      </p>

      <h2>2. The service</h2>
      <p>
        proxy-agent provides metered access to an AI chat model. Usage is
        prepaid in time credits and debited per second of actual model time.
        The service is provided on-demand: the model is started when you
        submit a request and stopped after an idle period.
      </p>

      <h2>3. Accounts</h2>
      <p>
        You are responsible for maintaining the security of your account and
        password, and for all activity that occurs under your account. You
        must be at least 18 years old, or the age of legal majority in your
        jurisdiction, to use the service. One person may maintain one
        account; do not share accounts.
      </p>

      <h2>4. Payment and credits</h2>
      <ul>
        <li>
          Credits are purchased in blocks (1h, 3h, 6h, 12h) and paid in
          cryptocurrency through a hosted gateway.
        </li>
        <li>
          Credits are debited for wall-clock model time per request. Failed or
          interrupted requests are only debited for model time actually
          consumed.
        </li>
        <li>
          Purchased credits are prepaid and are generally non-refundable once
          confirmed by the payment gateway. We may issue a refund at our
          discretion if the service materially fails to deliver.
        </li>
        <li>
          Credits have no cash value outside the service and are not
          transferable between accounts.
        </li>
      </ul>

      <h2>5. Acceptable use</h2>
      <p>
        The service offers an uncensored model: it does not apply
        vendor-side content filtering beyond the model&apos;s own behaviour.
        You are solely responsible for what you generate and how you use it.
        You must not use the service:
      </p>
      <ul>
        <li>
          To create, request, or distribute content that is illegal in your
          jurisdiction or ours, including content sexualising minors,
          blackmail, or threats of violence.
        </li>
        <li>To harass, defraud, or deceive real individuals (e.g. phishing, scam content).</li>
        <li>To generate malware, or to attack or probe the service or other systems.</li>
        <li>
          To circumvent metering, abuse concurrent-request limits, scrape the
          service, or resell access without a separate agreement.
        </li>
      </ul>
      <p>
        We may suspend or terminate accounts that violate these terms, to the
        extent technically possible.
      </p>

      <h2>6. Availability</h2>
      <p>
        The service depends on rented GPU infrastructure and third-party
        payment gateways. We do not guarantee uninterrupted availability, and
        we may modify, suspend, or discontinue any part of the service. If we
        discontinue the service entirely, prepaid credits that remain unused
        will be refunded on a pro-rata basis where operationally possible.
      </p>

      <h2>7. AI output disclaimer</h2>
      <p>
        Model responses may be inaccurate, offensive, or harmful, and do not
        represent our views. Output is generated by a language model, not a
        human. Do not rely on it for medical, legal, financial, or other
        consequential decisions. You assume all responsibility for how you
        use generated output.
      </p>

      <h2>8. Termination</h2>
      <p>
        You may stop using the service at any time. We may suspend or
        terminate your access for breach of these terms or for non-payment.
        Sections 4 (accrued credits), 7 (disclaimer), and 9–10 survive
        termination.
      </p>

      <h2>9. Limitation of liability</h2>
      <p>
        To the maximum extent permitted by law, the service is provided
        &quot;as is&quot; without warranties of any kind, and our aggregate
        liability to you is limited to the amount you paid us in the 30 days
        preceding the claim. We are not liable for indirect, incidental, or
        consequential damages, or for loss of data (keep your own copies of
        anything you care about).
      </p>

      <h2>10. Changes</h2>
      <p>
        We may update these terms. Material changes will be posted on this
        page with a new &quot;last updated&quot; date. Continued use after a
        change constitutes acceptance.
      </p>

      <h2>11. Contact</h2>
      <p>
        Questions about these terms:{" "}
        <a href="mailto:peskycipher@gmail.com">peskycipher@gmail.com</a>
      </p>

      <p style={{ marginTop: 48 }}>
        <Link href="/" className="muted">
          ← Back to home
        </Link>
      </p>
    </main>
  );
}